### PR TITLE
removed unnecessary banner

### PR DESCRIPTION
**Pull request by kouul**

### CODE REVIEW

**Comment by kouul** [comment]
image

**Comment by Abdur-rahmaanJ** [comment]
@greyli Thanks! Sorry for late perm, thought you already had since a long time!

**Comment by greyli** [comment]
@kouul The countdown area looks different on my side (cache cleared) with Chrome 83 & Windows 10.

image

**Comment by Abdur-rahmaanJ** [comment]
@greyli what browser? opera private mode gives me:

opera_flaskcon

**Comment by Abdur-rahmaanJ** [comment]
Seems an issue to the right of numbers

**Comment by greyli** [comment]
The image above is on Chrome 83. I also tested it on Firefox and Edge, Firefox is OK, but not good on Edge:

image

**Comment by kouul** [comment]
oh.. this is bad. The error with the countdown border thingy is because of the width. I fixed it.
Let me test on Edge now. I completely forgot the old Edge.

**Comment by Abdur-rahmaanJ** [comment]
Haha Edge seems like a joke XD. Btw preparing to tell people that the the site is open source. btw added an edit on github text on nav

**Comment by greyli** [comment]
> preparing to tell people that the site is open source. btw added an edit on github text on nav

That's a good idea :)

**Comment by kouul** [comment]
@greyli I just tested the site on Edge 44 Windows 10. Everything looks normal. Which version of Edge is your screenshot from?

**Comment by Abdur-rahmaanJ** [comment]
Btw @greyli you know how to add subfolder in jinja? We have too many files in templates. We'd like to include partials/.... in main.html

**Comment by greyli** [comment]
> Which version of Edge is your screenshot from?

Edge 42.

> you know how to add subfolder in Jinja? We'd like to include partials/.... in main.html

Yes, I will do it.

**Comment by greyli** [comment]
@Abdur-rahmaanJ Check out https://github.com/FlaskCon/website/pull/12.

**Pull request merged**
