### PR TITLE
changed cards design and schedule design

### PR DESCRIPTION
**Pull request by kouul**
Changed the design of organiser-cards and timer countdown based on https://github.com/FlaskCon/website/issues/16. Thanks to @pjshu
image
image

Also changed the schedule style. See images below:
image
image
image

### CODE REVIEW

**Comment by Abdur-rahmaanJ** [comment]
Why is miguel's description hidden?

**Comment by Abdur-rahmaanJ** [comment]
Also its 3 days, 3 4 and 5 july. 4 5 talks 3 interviews

**Comment by kouul** [comment]
> Why is miguel's description hidden?
I took a screenshot, that's why it's not showing everything. Here is an image of the whole page

image

**Comment by Abdur-rahmaanJ** [comment]
Seems really nice, sorry my last comment was i thought it was one image

**Comment by Abdur-rahmaanJ** [comment]
If responsiveness test ok, you can merge

**Pull request merged**
